CREATE EXTENSION IF NOT EXISTS vector;

-- The project starts empty, so create the commerce tables needed by the
-- quantitative-query path. The ALTER statements below also make this safe to
-- apply when a products table is supplied by a future application migration.
CREATE TABLE IF NOT EXISTS public.products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  price NUMERIC(12, 2),
  stock INTEGER NOT NULL DEFAULT 0,
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.products
  ADD COLUMN IF NOT EXISTS description TEXT,
  ADD COLUMN IF NOT EXISTS embedding vector(1536);

CREATE TABLE IF NOT EXISTS public.invoices (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  total NUMERIC(12, 2) NOT NULL DEFAULT 0,
  status TEXT NOT NULL DEFAULT 'issued',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.invoice_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  invoice_id BIGINT NOT NULL REFERENCES public.invoices(id) ON DELETE CASCADE,
  product_id BIGINT REFERENCES public.products(id) ON DELETE SET NULL,
  quantity INTEGER NOT NULL DEFAULT 1 CHECK (quantity > 0),
  unit_price NUMERIC(12, 2) NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS public.documents (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  content TEXT NOT NULL,
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  embedding vector(1536) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS products_embedding_hnsw_idx
  ON public.products USING hnsw (embedding vector_cosine_ops);

CREATE INDEX IF NOT EXISTS documents_embedding_hnsw_idx
  ON public.documents USING hnsw (embedding vector_cosine_ops);

ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.invoices ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.invoice_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.documents ENABLE ROW LEVEL SECURITY;

-- Browser code talks to the Edge Functions. Direct table access remains
-- closed by RLS so an anon key cannot bypass the server-side RAG boundary.
REVOKE ALL ON public.products, public.invoices, public.invoice_items, public.documents
  FROM anon, authenticated;

CREATE OR REPLACE FUNCTION public.match_documents(
  query_embedding vector(1536),
  match_count INTEGER DEFAULT 5,
  match_threshold DOUBLE PRECISION DEFAULT 0.70
)
RETURNS TABLE (
  id BIGINT,
  content TEXT,
  metadata JSONB,
  similarity DOUBLE PRECISION
)
LANGUAGE SQL
STABLE
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
  SELECT
    d.id,
    d.content,
    d.metadata,
    1 - (d.embedding <=> query_embedding) AS similarity
  FROM public.documents AS d
  WHERE d.embedding IS NOT NULL
    AND 1 - (d.embedding <=> query_embedding) >= GREATEST(match_threshold, 0)
  ORDER BY d.embedding <=> query_embedding
  LIMIT LEAST(GREATEST(match_count, 1), 50);
$$;

CREATE OR REPLACE FUNCTION public.match_products(
  query_embedding vector(1536),
  match_count INTEGER DEFAULT 5,
  match_threshold DOUBLE PRECISION DEFAULT 0.70
)
RETURNS TABLE (
  id BIGINT,
  name TEXT,
  description TEXT,
  price NUMERIC,
  stock INTEGER,
  metadata JSONB,
  similarity DOUBLE PRECISION
)
LANGUAGE SQL
STABLE
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
  SELECT
    p.id,
    p.name,
    p.description,
    p.price,
    p.stock,
    p.metadata,
    1 - (p.embedding <=> query_embedding) AS similarity
  FROM public.products AS p
  WHERE p.embedding IS NOT NULL
    AND 1 - (p.embedding <=> query_embedding) >= GREATEST(match_threshold, 0)
  ORDER BY p.embedding <=> query_embedding
  LIMIT LEAST(GREATEST(match_count, 1), 50);
$$;

-- A second server-side guard for the SQL path. The ask function performs the
-- same checks before calling this RPC, while this function protects the DB if
-- it is ever invoked directly with the project admin key.
CREATE OR REPLACE FUNCTION public.run_safe_readonly_query(sql_query TEXT)
RETURNS SETOF JSONB
LANGUAGE PLPGSQL
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
  statement TEXT := btrim(sql_query);
BEGIN
  IF length(statement) = 0 OR length(statement) > 8000 THEN
    RAISE EXCEPTION 'Query length is invalid';
  END IF;

  IF statement !~* '^SELECT[[:space:]]'
     OR statement ~ '[;]'
     OR statement ~* '\b(INSERT|UPDATE|DELETE|DROP|ALTER|TRUNCATE|CREATE|GRANT|REVOKE|MERGE|CALL|COPY|VACUUM|ANALYZE|SET|SHOW|LOCK|FOR[[:space:]]+UPDATE|FOR[[:space:]]+SHARE)\b'
     OR statement ~* '--|/\*|\*/' THEN
    RAISE EXCEPTION 'Only a single read-only SELECT query is allowed';
  END IF;

  RETURN QUERY EXECUTE format(
    'SELECT to_jsonb(row_data) FROM (%s) AS row_data LIMIT 50',
    statement
  );
END;
$$;

GRANT EXECUTE ON FUNCTION public.match_documents(vector, INTEGER, DOUBLE PRECISION)
  TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.match_products(vector, INTEGER, DOUBLE PRECISION)
  TO anon, authenticated;
